#!/bin/sh
set -eu

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$KEYCLOAK_DB_USER') THEN
    CREATE ROLE $KEYCLOAK_DB_USER LOGIN PASSWORD '$KEYCLOAK_DB_PASSWORD';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE $KEYCLOAK_DB_NAME'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$KEYCLOAK_DB_NAME')\gexec

GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_NAME TO $KEYCLOAK_DB_USER;
SQL
