create table user_profile (
  id bigint generated by default as identity primary key,
  keycloak_id varchar(128) not null unique,
  email varchar(255) not null,
  full_name varchar(255) not null,
  role_snapshot varchar(32) not null,
  marketing_opt_in boolean not null default false,
  suspended boolean not null default false,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table studio (
  id bigint generated by default as identity primary key,
  slug varchar(120) not null unique,
  name varchar(255) not null,
  neighborhood varchar(120) not null,
  discipline varchar(80) not null,
  description varchar(1000) not null,
  image_url varchar(500) not null,
  featured boolean not null default false,
  approved boolean not null default false,
  rating numeric(3,2) not null default 4.80,
  base_price numeric(10,2) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table instructor (
  id bigint generated by default as identity primary key,
  studio_id bigint not null references studio(id),
  name varchar(255) not null,
  bio varchar(1000) not null,
  avatar_url varchar(500) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table class_template (
  id bigint generated by default as identity primary key,
  studio_id bigint not null references studio(id),
  instructor_id bigint not null references instructor(id),
  title varchar(255) not null,
  discipline varchar(80) not null,
  description varchar(1000) not null,
  duration_minutes integer not null,
  default_price numeric(10,2) not null,
  cancellation_window_hours integer not null,
  capacity integer not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table class_session (
  id bigint generated by default as identity primary key,
  template_id bigint not null references class_template(id),
  starts_at timestamp not null,
  ends_at timestamp not null,
  price numeric(10,2) not null,
  capacity integer not null,
  booked_count integer not null default 0,
  status varchar(32) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table booking (
  id bigint generated by default as identity primary key,
  session_id bigint not null references class_session(id),
  profile_id bigint not null references user_profile(id),
  status varchar(32) not null,
  payment_type varchar(32) not null,
  amount numeric(10,2) not null,
  credits_used integer not null default 0,
  stripe_checkout_session_id varchar(255),
  stripe_payment_intent_id varchar(255),
  cancellation_reason varchar(255),
  cancelled_at timestamp,
  attended_at timestamp,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table review (
  id bigint generated by default as identity primary key,
  booking_id bigint not null unique references booking(id),
  studio_id bigint not null references studio(id),
  profile_id bigint not null references user_profile(id),
  rating integer not null,
  body varchar(1000) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);
