create table subscription (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references user_profile(id),
  stripe_subscription_id varchar(255) unique,
  stripe_customer_id varchar(255),
  credits_remaining integer not null default 10,
  status varchar(32) not null,
  plan_name varchar(120) not null,
  renews_at timestamp,
  cancelled_at timestamp,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table payment (
  id bigint generated by default as identity primary key,
  booking_id bigint references booking(id),
  stripe_payment_intent_id varchar(255) unique,
  stripe_checkout_session_id varchar(255) unique,
  stripe_customer_id varchar(255),
  stripe_subscription_id varchar(255),
  amount numeric(10,2) not null,
  platform_commission numeric(10,2) not null,
  currency varchar(8) not null,
  status varchar(32) not null,
  payment_type varchar(32) not null,
  refund_reason varchar(255),
  refunded_at timestamp,
  idempotency_key varchar(255),
  created_at timestamp not null,
  updated_at timestamp not null
);

create table invoice (
  id bigint generated by default as identity primary key,
  payment_id bigint references payment(id),
  stripe_invoice_id varchar(255) unique,
  invoice_number varchar(120) not null,
  hosted_invoice_url varchar(500),
  currency varchar(8) not null,
  amount numeric(10,2) not null,
  status varchar(32) not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

create table processed_stripe_event (
  id bigint generated by default as identity primary key,
  event_id varchar(255) not null unique,
  event_type varchar(255) not null,
  processed_at timestamp not null,
  created_at timestamp not null,
  updated_at timestamp not null
);

insert into studio (slug, name, neighborhood, discipline, description, image_url, featured, approved, rating, base_price, created_at, updated_at)
values
  ('solstice-yoga', 'Solstice Yoga', 'Notting Hill', 'Yoga', 'Low-lit vinyasa, strong flows, calm energy.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80', true, true, 4.9, 24.00, now(), now()),
  ('pulse-hiit', 'Pulse HIIT Lab', 'Shoreditch', 'HIIT', 'Short, sharp, high-energy intervals with good music.', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80', true, true, 4.8, 28.00, now(), now()),
  ('moss-pilates', 'Moss Pilates', 'King''s Cross', 'Pilates', 'Precision-led reformer and mat work for modern schedules.', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80', false, true, 4.7, 26.00, now(), now());

insert into instructor (studio_id, name, bio, avatar_url, created_at, updated_at)
select id, 'Mia Torres', 'Former dancer, neighborhood coach, and studio regular.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80', now(), now() from studio where slug = 'solstice-yoga';

insert into instructor (studio_id, name, bio, avatar_url, created_at, updated_at)
select id, 'Jamal Reed', 'High-output interval coach with a friendly cue style.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80', now(), now() from studio where slug = 'pulse-hiit';

insert into instructor (studio_id, name, bio, avatar_url, created_at, updated_at)
select id, 'Eva Stein', 'Pilates instructor focused on posture and core strength.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=800&q=80', now(), now() from studio where slug = 'moss-pilates';

insert into class_template (studio_id, instructor_id, title, discipline, description, duration_minutes, default_price, cancellation_window_hours, capacity, created_at, updated_at)
select s.id, i.id, 'Sunrise Flow', 'Yoga', 'An energizing morning flow that opens the day.', 60, 24.00, 12, 18, now(), now() from studio s join instructor i on i.studio_id = s.id where s.slug = 'solstice-yoga';

insert into class_template (studio_id, instructor_id, title, discipline, description, duration_minutes, default_price, cancellation_window_hours, capacity, created_at, updated_at)
select s.id, i.id, 'After-Work Burn', 'HIIT', 'Fast-paced conditioning with recovery built in.', 45, 28.00, 6, 14, now(), now() from studio s join instructor i on i.studio_id = s.id where s.slug = 'pulse-hiit';

insert into class_template (studio_id, instructor_id, title, discipline, description, duration_minutes, default_price, cancellation_window_hours, capacity, created_at, updated_at)
select s.id, i.id, 'Core Reset', 'Pilates', 'A precise, low-impact session that still leaves a mark.', 50, 26.00, 12, 16, now(), now() from studio s join instructor i on i.studio_id = s.id where s.slug = 'moss-pilates';

insert into class_session (template_id, starts_at, ends_at, price, capacity, booked_count, status, created_at, updated_at)
select id, timestamp '2030-01-01 08:00:00', timestamp '2030-01-01 09:00:00', default_price, capacity, 6, 'SCHEDULED', timestamp '2030-01-01 00:00:00', timestamp '2030-01-01 00:00:00' from class_template;
